### ISSUE TITLE
sendmsg() failed (9: Bad file descriptor)

### ISSUE THREAD

**Issue by ne0ark** [ZoeyVid/NPMplus#1113]
Hello,

I am getting the above error when I load:

https://www.authelia.com/integration/proxies/nginx/#proxyconf
https://www.authelia.com/integration/proxies/nginx/#authelia-location-basicconf
https://www.authelia.com/integration/proxies/nginx-proxy-manager/#authelia-portal

Also, "proxy_buffers 64 256k;" is not supported and reverse breaks.

Thanks

**Comment by Zoey2936** [comment]
Hello, their config example are broken, please report it to them, not here. Thanks!

**Comment by ne0ark** [comment]
Yes, it seems like the issue was caused by the following:

real_ip_header X-Forwarded-For;
proxy_buffers 64 256k;

Any reason NPMplus would have errors when these are using in custom config?

**Comment by Zoey2936** [comment]
They are set by NPMplus and nginx is confused if they are set twice

**Comment by ne0ark** [comment]
@Zoey2936 Can we reopen this issue? As I am not sure what is causing

```
2024/09/25 18:07:53 [alert] 801#801: [lua] crowdsec.conf:3):8: [Crowdsec] Initialisation done
2024/09/25 18:07:53 [alert] 10258#10258: pthread_create() failed (11: Resource temporarily unavailable)
2024/09/25 18:07:53 [alert] 10291#10291: pthread_create() failed (11: Resource temporarily unavailable)
2024/09/25 18:07:54 [alert] 801#801: worker process 10258 exited with fatal code 2 and cannot be respawned
2024/09/25 18:07:54 [alert] 801#801: worker process 10291 exited with fatal code 2 and cannot be respawned
2024/09/25 18:08:16 [alert] 801#801: fork() failed while spawning "worker process" (11: Resource temporarily unavailable)
2024/09/25 18:08:16 [alert] 801#801: sendmsg() failed (9: Bad file descriptor)
```
It seems like the Ngnix worker process is crashing. I'm not sure what is causing this crash. Similar to:https://github.com/kubernetes/ingress-nginx/issues/6141

**Comment by Zoey2936** [comment]
What hardware/hoster do you use?

**Comment by ne0ark** [comment]
> What hardware/hoster do you use?

Hello, it seems like the issue was resolved. When I moved the docker to a custom network from the Bridge.

**Comment by AmaneSwiss** [comment]
Hello

I had this problem too..
> 2024/10/12 20:23:27 [alert] 10421#10421: pthread_create() failed (11: Resource temporarily unavailable)
2024/10/12 20:23:27 [alert] 6366#6366: fork() failed while spawning "worker process" (11: Resource temporarily unavailable)
2024/10/12 20:23:27 [alert] 6366#6366: sendmsg() failed (9: Bad file descriptor)
2024/10/12 20:23:27 [alert] 6366#6366: sendmsg() failed (9: Bad file descriptor)
2024/10/12 20:23:27 [alert] 6366#6366: sendmsg() failed (9: Bad file descriptor)
...

I have spent hours trying to solve this problem and finaly I found the problem in: `/usr/local/nginx/conf/nginx.conf`

The problem was with `worker_processes auto;`
I had to set this value manually to a maximum value of 123 to stop getting errors.
(of course, 123 threads or (max. threads - 5) are maximum. (“auto” does not work correctly)

I can only guess, but I think it was due to the number of cores on my CPU (128 threds) or something like that..
I using: AMD Ryzen Threadripper PRO 5995WX 64-Cores

My workaround for this is mapping this script in `NPMplus/data/etc/prerun/workaround.sh`
This will use half the threads of your processor.
```
#!/bin/bash
set -eu

# Half the number of threads of your CPU, you can also use MAX_THREDS="8" (that should actually be enough)
MAX_THREADS="$(($(nproc) / 2))"

# Path of nginx.conf
NGINX_CONFIG_DIR="/usr/local/nginx/conf/nginx.conf"

# Workaround for using $MAX_THREADS as worker_processes
sed -ir "s/^worker_processes\s*auto;/worker_processes $MAX_THREADS;/" "$NGINX_CONFIG_DIR"

# Prevents the creation of multiple '#' when restarting the container
sed -ir "s/^##*user\s*root;/#user root;/" "$NGINX_CONFIG_DIR"
```
This also fixes the problem that `#user root;` gets a “#” every time when restarting the container..

I hope this helps others too.
Regards

**Comment by Zoey2936** [comment]
Hello, 
as the error seems to be related to a broken `worker_processes auto;` can you please report it to freenginx please? Thanks!
The other issue with multiplying # before `user root;` in non root mode will be fixed in the next release (already fixed in develop)

**Comment by EvanCBrummert1** [comment]
Easiest fix is to use CPU pinning for the docker
