### ISSUE TITLE
Support changing the PUID/PGID

### ISSUE THREAD

**Issue by dontcrash** [ZoeyVid/NPMplus#239]
+1 for this please, I would love to be able to run this as nobody instead of root

**Comment by Zoey2936** [comment]
I will see if I get it running, in best case it will only require changes in the nginx.conf, some chown commands and a user switch in the start.sh

**Comment by Zoey2936** [comment]
@dontcrash can you please test #246 ?

**Comment by dontcrash** [comment]
> @dontcrash can you please test #246 ?

Seems to work ok! No more root :D

**Comment by Zoey2936** [comment]
merged it into develop, please test again

**Comment by Zoey2936** [comment]
I‘ve pushed it to latest

**Comment by dontcrash** [comment]
Works fine on my Ubuntu server, tried it on Mac for funsies but the nobody account is -2, unsure if this is a Mac specific quirk that can be addressed by making a new user with no shell, no login etc and a >0 integer or if accepting negative integers would solve it

**Comment by Zoey2936** [comment]
what do you mean? the user creation is done this way: `useradd -o -u "$PUID" -U -d /tmp/npmuserhome -s /bin/false npmuser`, like the original npm does it, there is no and PUID has no checks, so it can be a negative number, but i think the useradd command does not support this

**Comment by dontcrash** [comment]
Please disregard, I was doing something definitely non-standard!

**Comment by Zoey2936** [comment]
So no issue here, or did I misunderstand something?

**Comment by dontcrash** [comment]
No issue :)

**Comment by Zoey2936** [comment]
@dontcrash but one question for my interests, how did you found my fork?

**Comment by dontcrash** [comment]
I was looking for a version of npm that didn't use a version of OpenSSL from three years ago, and a version of nginx from a year ago!

**Comment by Modged** [comment]
Hi @Zoey2936,

I don,'t know if you prefer me to open a new issue ?
I hope I am not annoying you by posting here.

I’m testing NPMPlus (zoeyvid/nginx-proxy-manager) on a Synology NAS and I’m facing an issue related to port binding when running NPMPlus as a non-root user.

Problem ;
When NPMPlus runs as the default npm user (non-root), nginx fails to start with:
```
bind() to 0.0.0.0:81 failed (13: Permission denied)
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
```

This happens even if I expose different external ports via Docker (-p 8282:8181, etc.), because NPMPlus always tries to bind internally to ports 80/81/443.

What I have tested ;

Mapping to high ports only (e.g. -p 8282:8181)
=> Did not work because NPMPlus still binds internally to 81.

Using Linux sysctl or NET_BIND_SERVICE :

`--sysctl net.ipv4.ip_unprivileged_port_start=0`
=> Fails on Synology with:
`open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory`

**This sysctl is not supported on Synology / restricted kernels.**

`--cap-add=NET_BIND_SERVICE \`
=> no change

Running NPMPlus as root (PUID=0, PGID=0)
=> Works correctly, nginx can bind to ports 80/81/443 and the webapp starts fine.

So ... there is my conclusion ;

On systems like Synology where :
privileged ports (<1024) require root
and ip_unprivileged_port_start is not available

NPMPlus cannot run as non-root unless it supports configurable internal ports or alternative binding mechanisms.

So ... Possible improvements :

It would be great if NPMPlus could support one of the following:
Configurable internal ports for admin / HTTP / HTTPS
Or an option to avoid binding to privileged ports internally
Or at last better documentation that root is required on platforms like Synology.

This would make NPMPlus easier to run securely on NAS systems and restricted kernels.

Thanks for your work on this project!

**Comment by Zoey2936** [comment]
changing the ports is supported, just look in the compose.yaml
