### ISSUE TITLE
Logging settings by proxy host + modsecurity blocking log check function suggestion

### ISSUE THREAD

**Issue by dalso0418** [ZoeyVid/NPMplus#496]
Hello. It's been a while since I said hello.
Is it possible to add an option to leave nginx log like the existing npm? It would be nice to add an option for log to leave separately even if it is not for proxy host.

In addition, it would be fantastic if there was an option to view logs blocked by modsecurity in webui and make exceptions for that rule id.

Thank you for the good project :)

**Comment by Zoey2936** [comment]
For the first, I think you mean access logs, but sorry, I will not add them back, because they would break EU law.

For the seccond, because they are logged to the docker logs, NPMplus would need to have access to the docker socket to read them, which is too unsecure from my view.
NPMplus also doesn't log all IDs which causes the block to the console, since without debug logging this is not possible (which would be too much of logging). But I can make the REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example and RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example editable

**Comment by Zoey2936** [comment]
added in new release

**Comment by fa-ve** [comment]
There is a way to do IP masking in NGNIX,: https://www.nginx.com/blog/data-masking-user-privacy-nginscript/ it would be useful for troubleshooting to have some logs. As I understand you're from Germany and the privacy rules are even stronger than in the rest of Europe

**Comment by Zoey2936** [comment]
That would be an option... 
But I just want to mention that you have the custom folder in /opt/npm/nginx, where you can enable the access_log for yourself. 
But if I add an option like mentioned by you, I would add only one log file and not for each nginx host one, and also I wouldn't add any log rotation.

**Comment by fa-ve** [comment]
Can you explain how? where you can enable the access_log for yourself 
As I'm still leaning :)

As I want to use when needed: https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager but then I need log files.

**Comment by Zoey2936** [comment]
in the `/opt/npmplus/nginx/custom_*.conf` files you can configure the logs how you want: https://nginx.org/en/docs/http/ngx_http_log_module.html

**Comment by dalso0418** [comment]
Thank you for your reply :) I'll check it out!
